/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author simon
 */
public class Menu extends javax.swing.JFrame {
    JMenuBar barraMenu;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setJMenuBar(initMenu());
    }
    public JMenuBar initMenu(){
         barraMenu = new JMenuBar();
        JMenu jMenuOpera = new JMenu("Gestion");
        JMenu jMenuProgra = new JMenu("Progama");
        JMenuItem jItem1 = new JMenuItem("Agregar Personal");
        JMenuItem jItem2 = new JMenuItem("Listar Personal");
        JMenuItem jItem3 = new JMenuItem("Modificar Personal");
        JMenuItem jItem4 = new JMenuItem("Eliminar Personal");
        JMenuItem jItem5 = new JMenuItem("Cerrar");
        
        jItem1.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent ev) {
                JFrame frameAgregar = new Agregar();
                frameAgregar.setVisible(true);
                dispose();
        }});
        jItem2.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent ev) {
                JFrame frameListar = new Listar();
                frameListar.setVisible(true);
                dispose();
        }});
        jItem3.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent ev) {
                JFrame frameListar = new Modificar();
                frameListar.setVisible(true);
                dispose();
        }});
        jItem4.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent ev) {
                JFrame frameListar = new Eliminar();
                frameListar.setVisible(true);
                
        }});
        jItem5.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent ev) {
                dispose();
        }});
        
        jMenuOpera.add(jItem1);
        jMenuOpera.add(jItem2);
        jMenuOpera.add(jItem3);
        jMenuOpera.add(jItem4);
        jMenuProgra.add(jItem5);
        barraMenu.add(jMenuOpera);
        barraMenu.add(jMenuProgra);
        barraMenu.setVisible(true);
        return barraMenu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
